
$RNFirebaseAsStaticFramework = true
$RNFirebaseAnalyticsWithoutAdIdSupport=true
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# pod 'Firebase/Analytics'
# pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'

platform :ios, '11.0'
inhibit_all_warnings!

pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'

target 'SmartBuildings' do
  config = use_native_modules!
    use_react_native!(
    :path => config["reactNativePath"],
    # to enable hermes on iOS, change `false` to `true` and then install pods
 )
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  # pod 'RNCallKeep', :path => '../node_modules/react-native-callkeep'

  # pod 'RNVoipPushNotification', :path => '../node_modules/react-native-voip-push-notification'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'SmartBuildingsTests' do
    inherit! :complete  

    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.


  # use_flipper!({ 'Flipper-Folly' => '2.5.2', 'Flipper' => '0.120.0', 'Flipper-RSocket' => '1.4' })
  # use_flipper!({ 'Flipper' => '0.96.0', 'Flipper-Folly' => '~> 2.6', 'Flipper-RSocket' => '~> 1.4' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  #   # react_native_post_install(installer)
  # end
  
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
          end
      end
  end
  

  # post_install do |installer|
  #     # flipper_post_install(installer)
  #     installer.pods_project.targets.each do |target|
  #       target.build_configurations.each do |config|
  #         config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
  #       end
  #     end
  #  end


#    post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['ENABLE_BITCODE'] = 'NO'
#         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#               config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        
#     end
#   end
# end

end
