import Animated, {
  Layout,
  FadeIn,
  FadeInRight,
  FadeInLeft,
  FadeInUp,
  FadeInDown,
  BounceIn,
  BounceInRight,
  BounceInLeft,
  BounceInUp,
  BounceInDown,
  FlipInYRight,
  FlipInYLeft,
  FlipInXUp,
  FlipInXDown,
  FlipInEasyX,
  FlipInEasyY,
  StretchInX,
  StretchInY,
  ZoomIn,
  ZoomInRotate,
  ZoomInRight,
  ZoomInLeft,
  ZoomInUp,
  ZoomInDown,
  ZoomInEasyUp,
  ZoomInEasyDown,
  SlideInRight,
  SlideInLeft,
  SlideInUp,
  SlideInDown,
  LightSpeedInRight,
  LightSpeedInLeft,
  PinwheelIn,
  RollInLeft,
  RotateInDownLeft,
  RotateInDownRight,
  RotateInUpLeft,
  RotateInUpRight,
} from "react-native-reanimated";
let AnimationList = [
  { name: "Layout", action: Layout },
  { name: "FadeIn", action: FadeIn },
  { name: "FadeInRight", action: FadeInRight },
  { name: "FadeInLeft", action: FadeInLeft },
  { name: "FadeInUp", action: FadeInUp },
  { name: "FadeInDown", action: FadeInDown },
  { name: "BounceIn", action: BounceIn },
  { name: "BounceInRight", action: BounceInRight },
  { name: "BounceInLeft", action: BounceInLeft },
  { name: "BounceInUp", action: BounceInUp },
  { name: "BounceInDown", action: BounceInDown },
  { name: "FlipInYRight", action: FlipInYRight },
  { name: "FlipInYLeft", action: FlipInYLeft },
  { name: "FlipInXUp", action: FlipInXUp },
  { name: "FlipInXDown", action: FlipInXDown },
  { name: "FlipInEasyX", action: FlipInEasyX },
  { name: "FlipInEasyY", action: FlipInEasyY },
  { name: "StretchInX", action: StretchInX },
  { name: "StretchInY", action: StretchInY },
  { name: "ZoomIn", action: ZoomIn },
  { name: "ZoomInRotate", action: ZoomInRotate },
  { name: "ZoomInRight", action: ZoomInRight },
  { name: "ZoomInLeft", action: ZoomInLeft },
  { name: "ZoomInUp", action: ZoomInUp },
  { name: "ZoomInDown", action: ZoomInDown },
  { name: "ZoomInEasyUp", action: ZoomInEasyUp },
  { name: "ZoomInEasyDown", action: ZoomInEasyDown },
  { name: "SlideInRight", action: SlideInRight },
  { name: "SlideInLeft", action: SlideInLeft },
  { name: "SlideInUp", action: SlideInUp },
  { name: "SlideInDown", action: SlideInDown },
  { name: "LightSpeedInRight", action: LightSpeedInRight },
  { name: "LightSpeedInLeft", action: LightSpeedInLeft },
  { name: "PinwheelIn", action: PinwheelIn },
  { name: "RollInLeft", action: RollInLeft },
  { name: "RotateInDownLeft", action: RotateInDownLeft },
  { name: "RotateInDownRight", action: RotateInDownRight },
  { name: "RotateInUpLeft", action: RotateInUpLeft },
  { name: "RotateInUpRight", action: RotateInUpRight },
];

export const customAnimation = (type, dur, dly, i) => {
  let Type = AnimationList.filter((animate) => {
    if (animate?.name == type) return animate;
  });
  return {
    entering: Type[0].action?.duration(dur).delay(i * dly),
    layout: Type[0].action?.restSpeedThreshold(),
  };
};
