// profile
export const SET_THEME = "SET_THEME";
export const DOCUMENT_FOLDER = "DOCUMENT_FOLDER";
export const PROFILE_INPUT_CHANGE = "PROFILE_INPUT_CHANGE";
export const LOGIN_INPUT_CHANGE = "LOGIN_INPUT_CHANGE";
export const DECREMENT = "DECREMENT";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_STARTED = "RESEND_OTP_STARTED";
export const RESEND_OTP_FAILURE = "RESEND_OTP_STARTED";
export const VALIDATION_ERROR_MESSAGE = "VALIDATION_ERROR_MESSAGE";
export const SUBMIT_CONTROL = "SUBMIT_CONTROL";
export const SET_USER = "SET_USER";
export const SET_BLE = "SET_BLE";
export const RESET_STATE_PROFILE = "RESET_STATE_PROFILE";
export const ON_SUBSCRIBE_NOTICE = "ON_SUBSCRIBE_NOTICE";
export const LIST_SUBSCRIPTION = "LIST_SUBSCRIPTION";
export const LIST_NOTICE = "LIST_NOTICE";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const USER_IMAGE = "USER_IMAGE";
export const VALIDATION_ERROR_RESET = "VALIDATION_ERROR_RESET";

//registration
// export const FAMILY_LIST = 'FAMILY_LIST';
export const RESIDENT_LIST = "RESIDENT_LIST";
export const VEHICLE_LIST = "VEHICLE_LIST";
export const FAMILY_REGISTRATION = "FAMILY_REGISTRATION";
export const RESIDENT_REGISTRATION = "RESIDENT_REGISTRATION";
export const ON_REGISTER_CHANGE = "ON_REGISTER_CHANGE";
export const ON_REGISTER_VALIDATION = "ON_REGISTER_VALIDATION";
export const STOP_LOADER = "STOP_LOADER";
export const CLEAR_STATE = "CLEAR_STATE";
export const RESIDENT_DETAILS = "RESIDENT_DETAILS";

//my visitor
export const LIST_MYVISITORS_DATA = "LIST_MYVISITORS_DATA";
export const ON_VISITOR_CHANGE = "ON_VISITOR_CHANGE";
export const SET_VISITOR_LOADER = "SET_VISITOR_LOADER";
export const SET_PHONE_AGGR = "SET_PHONE_AGGR";

//invite
export const INVITE_CHANGE = "INVITE_CHANGE";
export const INVITEE_VALIDATION = "INVITEE_VALIDATION";
export const INITIAL_VISITOR_INVITE = "INITIAL_VISITOR_INVITE";
export const SET_SUBVISITOR_LIST = "SET_SUBVISITOR_LIST";
export const LIST_MYINVITATIONS_DATA = "LIST_MYINVITATIONS_DATA";
export const SET_INVITE_LOADER = "SET_INVITE_LOADER";
export const ON_CLICK_INVITE = "ON_CLICK_INVITE";
export const ON_RESET_FILTER = "ON_RESET_FILTER";
export const INVITE_RESET = "INVITE_RESET";
export const CLEAR_VAL = "CLEAR_VAL";
export const INVITE_FETCH_DATA_REQUEST = "INVITE_FETCH_DATA_REQUEST";
export const INVITE_FETCH_DATA_SUCCESS = "INVITE_FETCH_DATA_SUCCESS";
export const INVITE_FETCH_DATA_FAILURE = "INVITE_FETCH_DATA_FAILURE";
export const INVITE_RESET_DATA = "INVITE_RESET_DATA";

//home
export const HOME_PAGE_LOADER = "HOME_PAGE_LOADER";
export const HOME_PAGE_DATA = "HOME_PAGE_DATA";
export const RESET_STATE = "RESET_STATE";
export const SHOW_CASE_TRIGGER = "SHOW_CASE_TRIGGER";
export const SET_HOME_LOADER = "SET_HOME_LOADER";

//switch Unit
export const SWITCH_UNIT = "SWITCH_UNIT";
export const LIST_UNITS = "LIST_UNITS";

// complaints
export const LIST_COMPLAINTS = "LIST_COMPLAINTS";
export const ON_COMPLAINTS_CHANGE = "ON_COMPLAINTS_CHANGE";
export const COMPLAINT_VALIDATION = "COMPLAINT_VALIDATION";
export const COMPLAINTS_CHANGE = "COMPLAINTS_CHANGE";
export const SET_COMPLAINT_DATA_LIST = "SET_COMPLAINT_DATA_LIST";

// facility
export const ON_FACILITY_DATA_CHANGE = "ON_FACILITY_DATA_CHANGE";
export const ON_FACILITY_QUESTION_CHANGE = "ON_FACILITY_QUESTION_CHANGE";
export const FACILITY_VALIDATION = "FACILITY_VALIDATION";
export const FACILITY_CHANGE = "FACILITY_CHANGE";
export const ON_CLICK_FACILITIES = "ON_CLICK_FACILITIES";
export const FACILITY_RESET = "FACILITY_RESET";
export const FACILITY_FETCH_DATA_REQUEST = "FACILITY_FETCH_DATA_REQUEST";
export const FACILITY_FETCH_DATA_SUCCESS = "FACILITY_FETCH_DATA_SUCCESS";
export const FACILITY_FETCH_DATA_FAILURE = "FACILITY_FETCH_DATA_FAILURE";
export const FACILITY_RESET_DATA="FACILITY_RESET_DATA"
//login
export const RESET_STATE_LOGIN = "RESET_STATE_LOGIN";
export const BLE_TRIGGER = "BLE_TRIGGER";
// community
export const ON_COMMUNITY_CHANGE = "ON_COMMUNITY_CHANGE";
export const COMMUNITY_RESET = "COMMUNITY_RESET";
export const ON_LIKE_APPLY = "ON_LIKE_APPLY";
// video_call
export const CALL_LOGS = "CALL_LOGS";
export const ENTRIES = "ENTRIES";
export const RESET = "RESET";
export const CALL_LOGS_INITIALIZE = "CALL_LOGS_INITIALIZE";
export const LOADER = "LOADER";

//Local Help
export const LOCALHELP_ONCHANGE = "LOCALHELP_ONCHANGE";

//Feedbac
TICKET_RESET, LIST_TICKET_DATA, ON_RESET_FILTER, SET_TICKET_LOADER;
export const TICKET_RESET = "TICKET_RESET";
export const LIST_TICKET_DATA = "LIST_TICKET_DATA";
export const SET_TICKET_LOADER = "SET_TICKET_LOADER";
export const TICKET_CHANGE = "SET_TICKET_LOADER";
export const ON_CLICK_TICKET = "ON_CLICK_TICKET";
